java_binary(
    name = "build_worker",
    main_class = "com.google.devtools.build.remote.BuildWorker",
    visibility = ["//visibility:public"],
    runtime_deps = ["//src/tools/build_worker/src/main/java/com/google/devtools/build/remote"],
)
